project:
  type: sdca-theme

website:
  title: "Almen praksis diabetesnetværk"
  site-url: "https://steno-aarhus.github.io/netvaerk-projektet/"
  repo-url: "https://github.com/steno-aarhus/netvaerk-projektet"
  navbar:
    pinned: true
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/"
        aria-label: "GitHub icon: Link to SDCA GitHub organization page"

format: sdca-theme-html

editor: 
  markdown:
    wrap: 72
    canonical: true
