---
title: "Vil I være med til at styrke det tværsektorielle samarbejde om behandlingen af type 2-diabetes?"
---

Så bliv en del af vores nye Almen praksis diabetesnetværk! Sammen med Steno Diabetes Center Aarhus (SDCA) og andre almen praksis får I mulighed for at målrette og kvalificere projekter, hvor sekundærsektoren kan understøtte diabetesbehandlingen i almen praksis. I netværket får I også mulighed for at sætte ord på de generelle udfordringer og problemstillinger, der fylder i behandlingen af jeres patienter med type 2-diabetes.    
Netværket løber over et år, og I vil blive honoreret for jeres deltagelse.  
Lyder det interessant? Kontakt os – vi ser frem til at høre fra jer! 

## Almen praksis skal involveres i udviklingsarbejdet

SDCA arbejder for, at alle med eller risiko for diabetes kan leve et godt liv. For at realisere denne vision er et tæt samarbejde med sundhedsområdets aktører afgørende, og her har almen praksis en unik ekspertise. SDCA ønsker derfor at involvere jer i det kommende, tværsektorielle udviklingsarbejde på type 2-diabetesområdet. Almen praksis diabetesnetværk etableres i sommeren 2025 og vil bestå af 5-7 almen praksis fra Region Midtjylland. 

**Målet med Almen praksis diabetesnetværket**

Netværkets mål er gennem åben dialog at identificere behandlingsudfordringer og afdække behovet for nye indsatser på type 2-diabetesområdet, samt at kvalificere tværsektorielle regionale og nationale indsatser. Som en del af netværket bidrager I aktivt med input, og derudover kan I, hvis der er fælles interesse herfor, afprøve konkrete indsatser i egen praksis.   

**Tidsforbrug og honorering**

Både læger og praksispersonale, der arbejder med patienter med type 2-diabetes i jeres praksis, deltager i netværket. Honoreringen baseres på et fastprishonorar, svarende til gældende konsulenthonorar for fuldtidslæge og -personale. Maks. honorar pr. praksis dækker 3 læger og 2 praksispersonale. Tidsforbrug behøver I ikke at registrere, men hver læge og praksispersonale forventes at deltage i og honoreres for følgende aktiviteter over et år: 

- 4 møder (ca. 3 timer pr. møde)

- Forberedelse inden hvert møde (2 timer pr. praksis pr. møde)

- Evaluering af netværket via interview med SDCA (1 time pr. praksis)

Hvis det bliver relevant at udvikle og afprøve konkrete indsatser i jeres praksis, vil der blive udbetalt særskilt honorar for dette. 

**Ansøgning og opstart**

Både enkelt- og flermandspraksis samt regionsklinikker opfordres til at ansøge. Ansøgning til at medvirke i netværket sker ved at sende en mail til SDCA på (ap.netvaerk@auh.rm.dk).  
I første omgang bedes I kun sende oplysninger om praksis-navn og adresse, samt kort beskrivelse af praksis (antal ansatte, antal patienter og lign.) 

Deadline for ansøgning er 25. april 2025.  

Vi forventer at afholde første møde i netværket senest juni 2025. 

**Organisering** 

Almen praksisnetværket etableres med 5-7 lægepraksis i en periode på ca. 12 måneder – fra tidlig sommer 2025 til sommeren 2026. Er der flere ansøgere, udvælger SDCA almen praksis ud fra et princip om størst mulig repræsentativitet i netværket, hvad angår geografisk placering, praksisstørrelse m.v. 

Netværket drives af SDCA, som er ansvarlig for at planlægge og afholde møder samt øvrige opgaver i relation til netværket. Hver praksis udpeger en tovholder, som varetager den løbende kommunikation med SDCA.   

## Kontakt 

### Kirsten Christensen 

::: {layout-ncol=2}

- tidligere praktiserende læge og nuværende praksiskonsulent ved SDCA 

- tlf 

- mail 

:::
